# Generated by Django 3.2 on 2021-04-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210423_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUS', 'Customer'), ('VEN', 'Vendor'), ('WHO', 'Wholesaler'), ('DEL', 'Delivery')], max_length=3),
        ),
    ]
